.\" Manpage for OpenSterogram.
.TH OPENSTEREOGRAM 6 "11 Nov 2011"
.SH NAME
OpenStereogram \- autostereogram generator
.SH SYNOPSIS
OpenStereogram
.SH DESCRIPTION
OpenStereogram is a java based application to generate autostereograms based on
user input. OpenStereograms were made popular through the book "Magic Eye," and
appear to "pop out" in 3D when viewed cross-eyed or wall-eyed.
.SH OPTIONS
The OpenStereogram command does not take any options.
